#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
export COLUMNS=80 TERM=dumb NO_COLOR=1
reference=skills/sysy/reference.md
mkdir -p "$(dirname "$reference")"
temporary=$(mktemp)
trap 'rm -f "$temporary"' EXIT

# Discover subcommands from help so adding commands also updates the reference.
render_help() {
    local help subcommand
    help=$(cargo run --quiet --locked --package sysy-cli -- "$@" --help | sed 's/[[:blank:]]*$//')
    {
        printf '\n## `sysy'
        if (($#)); then printf ' %s' "$@"; fi
        printf '`\n\n```text\n%s\n```\n' "$help"
    } >> "$temporary"
    while IFS= read -r subcommand; do
        render_help "$@" "$subcommand"
    done < <(printf '%s\n' "$help" | awk '
        /^Commands:$/ { commands = 1; next }
        /^[^ ]/ { commands = 0 }
        commands && /^  [a-z]/ && $1 != "help" { print $1 }
    ')
}

printf '# sysy command reference\n\nGenerated by `scripts/update-skill-reference.sh`. Do not edit by hand.\n' > "$temporary"
render_help
cp "$temporary" "$reference"
